#spring:
#  profiles:
#    active: @profileActive@


mybatis:
  type-aliases-package: com.jonesun.mybatis.entity
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    # 打印sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true

server:
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true